### ISSUE TITLE
shows mdx tags at the end of the article

### ISSUE THREAD

**Issue by piyush97** [piyush97/PiyushMehta.com#51]

**Comment by aswinawien** [comment]
Can I work on this ?

**Comment by piyush97** [comment]
Sure @aswinawien

**Comment by Aarush-Goyal** [comment]
Can I work on it?

**Comment by piyush97** [comment]
Sure @Aarush-Goyal

**Comment by shraddhahinge** [comment]
I'm a beginner, but I will try my best. Can I make PR of this issue?

**Comment by piyush97** [comment]
@shraddhahinge Why not! Go for it!

**Comment by mihirgupta0900** [comment]
Hey, can I work on this? Or is this taken?

**Comment by piyush97** [comment]
Go for it @mihirgupta0900

**Comment by aswinawien** [comment]
quick question, so  how should I show tags within each blog ? .. should I make a new component for that ? @piyush97

**Comment by piyush97** [comment]
Yes, you can make a new component and show it in the blog wherever you feel it looks good!
