### ISSUE TITLE
Create claps or applause or like feature

### ISSUE THREAD

**Issue by piyush97** [piyush97/PiyushMehta.com#52]
Liked an article? Don't you wanna press the like button? 

Let's Create it!

Can be similar to medium, facebook or any site! 

## Prerequisite 
* You have to be absolute beginner
* You should have a motivation for building this feature

## Reference
https://github.com/ColinEberhardt/applause-button

**Comment by abhaybhatt** [comment]
@piyush97  can i work on this?

**Comment by piyush97** [comment]
@abhaybhatt Go Ahead!

**Comment by abhaybhatt** [comment]
@piyush97 i am facing problem in setting up the project in my machine?

**Comment by piyush97** [comment]
Can you explain what issue you are facing @abhaybhatt ?

**Comment by sindhujaponnuru** [comment]
Hey! Great issue. Just clarifying, the requirement is to build a component that can be integrated into the end of the blog posts. Anything that I'm missing ?

**Comment by piyush97** [comment]
Correct @sindhujaponnuru

**Comment by sindhujaponnuru** [comment]
@piyush97 I'm unable to run the application :
![issue](https://user-images.githubusercontent.com/42408095/94773819-2ac15800-03da-11eb-8dc0-6b38446fdb70.PNG)

**Comment by piyush97** [comment]
@sindhujaponnuru 
```sh
npm install
```

```
npm run dev
```

**Comment by shraddhahinge** [comment]
@piyush97 I know React & JS pretty well, gatsby would be new for me but yeah I would love to explore and try to make the best out of it. I would add a clap animation or a favorite icon animation below the blog component. Can I PR?

**Comment by piyush97** [comment]
> @piyush97 I know React & JS pretty well, gatsby would be new for me but yeah I would love to explore and try to make the best out of it. I would add a clap animation or a favorite icon animation below the blog component. Can I PR?

Go for it!

**Comment by piyush97** [comment]
If facing issue
![image](https://user-images.githubusercontent.com/18229627/94774228-0d40be00-03db-11eb-9dfd-80224fcc9d89.png)

**Comment by bufgix** [comment]
How to store likes count?

**Comment by piyush97** [comment]
https://www.gatsbyjs.com/plugins/gatsby-source-firestore/
or infact any of the recommended Db
https://www.gatsbyjs.com/docs/sourcing-from-databases/

You can implement it and store the number of likes in the Db

:) 

> How do I store the likes count

@bufgix

**Comment by ogheneovo12** [comment]
is this issue currently assigned to anyone

**Comment by piyush97** [comment]
No @ogheneovo12

**Comment by khush31** [comment]
I'm a beginner in JS , Can I work on this ??

**Comment by piyush97** [comment]
Please go ahead @khush31

**Comment by khush31** [comment]
> Please go ahead @khush31

But I don't know where to contribute. Could you please Guide me

**Comment by AyushRajSharma** [comment]
can i also work on it

**Comment by Aditya-ds-1806** [comment]
Hey i made a PR, please review and let me know if it is fine! 
#101
