### ISSUE TITLE
(Hacktoberfest)[Super Easy] Update Readme and details

### ISSUE THREAD

**Issue by piyush97** [piyush97/PiyushMehta.com#57]
## Acceptance Criteria: 
* Readme should be updated with how to clone, install, and develop the project
* Any other required details if added will be appreciated

**Comment by piyush97** [comment]
@all-contributors please add Haqverdi for readme

**Comment by piyush97** [comment]
@all-contributors please add @Haqverdi for readme

**Comment by piyush97** [comment]
@all-contributors please add @Haqverdi for maintenance

**Comment by piyush97** [comment]
@all-contributors please add @piyush97 for blog

**Comment by Senpai1199** [comment]
Is this issue still open for working?
