### ISSUE TITLE
[Hacktoberfest][Easy] Add technical Blog or your experiences about tech you worked on!

### ISSUE THREAD

**Issue by piyush97** [piyush97/PiyushMehta.com#69]
Well it's your website too! Add your tech blogs and experiences! 👍🏽 
Your contribution will be given a shout out!!

**Comment by Shivam4747** [comment]
Can i work on this lol?

**Comment by ShashankAgarwal77** [comment]
I can create a blog on Debugging Tools and Technique for beginners in JavaScript

**Comment by ShashankAgarwal77** [comment]
You can assign me for technical blogs :)

**Comment by piyush97** [comment]
It’s for everyone, go for it guys!

**Comment by Harshi7016** [comment]
Can we add medium links of our blogs?

**Comment by ShashankAgarwal77** [comment]
Hello, @piyush97 actually I am still learning JavaScript and I don't know gatsby framework...so I don't know how to access codebase and push the blog...If you can help me with this issue. That would be very helpful :)
